### ISSUE TITLE
Doc rendering of toys tutorial is broken

### ISSUE THREAD

**Issue by jonas-eschle** [pyhf/pyhf-tutorial#13]
Hi all, looking through the tutorial page I've noticed that a tutorial was broken, namely https://pyhf.github.io/pyhf-tutorial/Toys.html#hypothesis-testing-revisited (if you scroll down to the very end of the output)

I assume it's a minor thing that you will be able to immediately fix, so I didn't dig into the error itself

**Comment by kratsg** [comment]
Which cell output are you referring to? Nothing is broken (or the CI wouldn't have passed).

**Comment by jonas-eschle** [comment]
I would have thought so too with the CI, but the output of the notebook is an error (if you click on the link, e.g. the first one, there is an error, right. Like this:
![Screenshot from 2021-11-27 16-11-40](https://user-images.githubusercontent.com/17454848/143686888-743b16d3-7c3e-4e41-bd00-776998b5d5e7.png)
?)

**Comment by jonas-eschle** [comment]
Sorry, I posted the wrong link, this one: https://pyhf.github.io/pyhf-tutorial/Toys.html#hypothesis-testing-revisited

**Comment by kratsg** [comment]
They keyboard interrupt is happening becaause of some interplay with jupyter rendering and tqdm. We can probably just turn off the progress bars to make the output a little bit shorter... @matthewfeickert ?

**Comment by matthewfeickert** [comment]
Nothing is "broken" in the sense that that code runs fine without errors. It isn't getting rendered out properly by Jupyter Book in the CI because I suspect that (as @kratsg points out) the number of iterations it is going through given the progress bar are triggering something in Jupyter Book that views it as an error.

> We can probably just turn off the progress bars to make the output a little bit shorter?

We can do that, but it would probably be worth updating the Jupyter Book first to the latest release and new setup schemas as the newer releases of Jupyter Book might handle this sort of thing nicer and not error at all. Leaving the progress bars on is nice for users who are stepping through the notebooks themselves.

**Comment by jonas-eschle** [comment]
> Nothing is "broken" in the sense that that code runs fine without errors. It isn't getting rendered out properly by Jupyter Book in the CI

yes agree, so it's a minor thing indeed!

Great, this seems to be fixed with #14 using the new Jupyter notebook. Many thanks!

**Comment by matthewfeickert** [comment]
> yes agree, so it's a minor thing indeed!

Minor but still relevant, so thanks for pointing this out. :) 
 
> Great, this seems to be fixed with #14 using the new Jupyter notebook.

Sorry this was a bit of an illusion caused by me testing PR #13 before I had it ready to go by altering the CI to deploy on any push event. So PR #13 resolves this, but PR #14 was still good to have.

**Comment by matthewfeickert** [comment]
The CI/CD is still having problems that I'm not able to understand right now. If I setup a new Python 3.9 virtual environment and install everything from scratch and run `make` I can't get the `KeyboardInterrupt` errors that are showing up in my locally rendered Jupyter Book.

**Comment by matthewfeickert** [comment]
Thanks for bringing this up (even though is was a long time ago), @jonas-eschle! We finally got it resolved in PR #61.
