### ISSUE TITLE
Small bugs in 'SimpleWorkspace.ipynb' and 'Combinations.ipynb'

### ISSUE THREAD

**Issue by sognetic** [pyhf/pyhf-tutorial#33]
Hi!

While clicking through the tutorials with pyhf 0.7.0. I noticed that in "SimpleWorkspace", the cell containing
```
workspace.get_measurement(poi_name="mu")
```
failed because the signature seems to have changed: `get_measurement() got an unexpected keyword argument 'poi_name'`

Similarly, in "Combinations" Cell 5 fails as the `combined_workspace` object doesn't seem to have a `parameters` attribute.
I'm not entirely sure about this second one though as it also fails with an AttributeError here: https://pyhf.github.io/pyhf-tutorial/Combinations.html
Is this intended behavior?

I know these are very small things, however as a new user any unexpected behavior is a bit confusing.

Cheers,
Moritz

**Comment by matthewfeickert** [comment]
Thanks for this Issue, @sognetic! Indeed, these are bugs, and I'm not sure how they got in. Seems like we need to tighten the constraints on runtime evaluations during the Jupyter Book build. I'll fix these today. :+1:

**Comment by matthewfeickert** [comment]
@sognetic This should be fixed now. Thanks for alerting us to this oversight and please let us know if you find anything else strange!

**Comment by sognetic** [comment]
@matthewfeickert Thank you for the nice tool and thanks for fixing this!
