### ISSUE TITLE
Link not working: Issue on page /HelloWorld.html

### ISSUE THREAD

**Issue by amanmdesai** [pyhf/pyhf-tutorial#74]
Hi,

In the following sentence: 

```
Nicely enough, pyhf is smart enough to let us know that, if for a model where 
, we’re not going to be able to catch it because our default bounds were bounding the parameter of interest from 
below at 0. For more information, see Equation 14 in [[10.7.2727]](https://arxiv.org/abs/10.7.2727).
```

The link to the arxiv paper does not work. 
Could you please fix it? 

Thanks
Aman

**Comment by matthewfeickert** [comment]
Ah this was a sloppy search and replace by me in PR https://github.com/pyhf/pyhf-tutorial/pull/43. Thanks for fixing it @kratsg. We should maybe think about adding broken link checks.
